spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/bchub?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      username: ENC(QdE1r3KDHPNa1jLmNvXbPQ==)
      password: ENC(+IATDsfYS1jwWqGqk0UCNQg9y9ipYxxD)
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    host: localhost
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
  # elasticsearch配置
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  # rabbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#mybatis-plus
mybatis-plus:
  global-config:
    #刷新Mapper，只在开发环境打开
    refresh: true
oss:
  tengxun:
    accessKey: ENC(8766zmEs12ipQTTkAEkrqsKst8ffi/qJg7RoA4A+3DJ3AHSTvcc/6IY/mphC53YO)
    secretKey: ENC(cX3KJIm0HdMG/5nydXoZHMUyLsY8Ogw/iAYKUe7hEiE4WFRr26zUVeRMCTUUFn6s)
    bucket: ap-chengdu
    bucketName: bchub-1257626064
    path: https://bchub-1257626064.cos.ap-chengdu.myqcloud.com
    qianzhui: bchub
jasypt:
  encryptor:
    password: bchub-jasypt